-- Create the database (PostgreSQL handles file locations differently)
-- CREATE DATABASE qlnv;

-- \c qlnv

-- Create tables
CREATE TABLE TrinhDoHocVan (
    MaTDHV SERIAL PRIMARY KEY,
    TenTDHV VARCHAR(50) NOT NULL,
    CreateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDelete BOOLEAN DEFAULT FALSE
);

CREATE TABLE NhanVien (
    MaNV SERIAL PRIMARY KEY,
    TenNV VARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi VARCHAR(100) NOT NULL,
    GioiTinh BOOLEAN DEFAULT FALSE,
    DienThoai VARCHAR(100) NOT NULL UNIQUE,
    SoCCCD VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(50) NOT NULL UNIQUE,
    CreateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDelete BOOLEAN DEFAULT FALSE,
    MaTDHV INT REFERENCES TrinhDoHocVan(MaTDHV)
);

CREATE TABLE Role (
    MaRole SERIAL PRIMARY KEY,
    Rolename VARCHAR(20) NOT NULL,
    CreatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE TaiKhoan (
    MaTaiKhoan SERIAL PRIMARY KEY,
    Username VARCHAR(20) NOT NULL,
    Password VARCHAR(200) NOT NULL,
    CreatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT FALSE,
    MaRole INT REFERENCES Role(MaRole),
    MaNV INT REFERENCES NhanVien(MaNV)
);

CREATE TABLE CaLam (
    MaCa SERIAL PRIMARY KEY,
    TenCa VARCHAR(255) NOT NULL,
    MoTa VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDisable BOOLEAN DEFAULT FALSE,
    ThoiGianBatDau VARCHAR(50) NOT NULL,
    ThoiGianKetThuc VARCHAR(50) NOT NULL,
    CreatedBy INT REFERENCES TaiKhoan(MaTaiKhoan)
);

CREATE TABLE ChucVu (
    MaCV SERIAL PRIMARY KEY,
    TenChucVu VARCHAR(100) NOT NULL,
    PhuCap NUMERIC(18, 2) DEFAULT 0,
    GhiChu VARCHAR(500) NOT NULL,
    CreateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDelete BOOLEAN DEFAULT FALSE,
    IsFullTime BOOLEAN DEFAULT FALSE
);

CREATE TABLE ChiTietChucVu (
    MaCTCV SERIAL PRIMARY KEY,
    MaCV INT NOT NULL REFERENCES ChucVu(MaCV),
    MaNV INT NOT NULL REFERENCES NhanVien(MaNV),
    NgayNhanChuc TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    CreateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDelete BOOLEAN DEFAULT FALSE
);

CREATE TABLE DangKyLichLam (
    MaLichLam SERIAL PRIMARY KEY,
    NgayDangKy TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    GioLam INT NOT NULL,
    TrangThai VARCHAR(50),
    CreateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDelete BOOLEAN DEFAULT FALSE,
    MaNV INT REFERENCES NhanVien(MaNV),
    MaCa INT REFERENCES CaLam(MaCa)
);

CREATE TABLE DieuChinhLuong (
    MaDCL SERIAL PRIMARY KEY,
    SoQuyetDinh VARCHAR(50) NOT NULL,
    NgayKyKet TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    NgayDieuChinhLuong TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    SoLuongMoi NUMERIC(18, 2) DEFAULT 0,
    CreateAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    MaNV INT REFERENCES NhanVien(MaNV)
);

CREATE TABLE KhenThuong (
    SoQD SERIAL PRIMARY KEY,
    NgayQD TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    Ten VARCHAR(100) NOT NULL,
    Loai VARCHAR(100) NOT NULL,
    HinhThuc VARCHAR(100) NOT NULL,
    SoTien NUMERIC(18, 2) DEFAULT 0,
    NoiDung VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT FALSE,
    MaNV INT REFERENCES NhanVien(MaNV)
);

CREATE TABLE Luong (
    MaLuong SERIAL PRIMARY KEY,
    Luong NUMERIC(18, 2) DEFAULT 0,
    KhoanTru NUMERIC(18, 2) DEFAULT 0,
    CreatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT FALSE,
    MaNV INT REFERENCES NhanVien(MaNV),
    PhuCap NUMERIC(18, 2) DEFAULT 0
);

CREATE TABLE MaXacNhan (
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL,
    code TEXT NOT NULL,
    expirationTime TEXT NOT NULL
);

-- Users and Roles
CREATE USER NVU01 WITH PASSWORD 'password';
CREATE USER NVU02 WITH PASSWORD 'password';
CREATE USER NVU03 WITH PASSWORD 'password';
CREATE USER NVU04 WITH PASSWORD 'password';
CREATE USER NVRead WITH PASSWORD 'password';
CREATE USER NVProfile WITH PASSWORD 'password';

GRANT CONNECT ON DATABASE qlnv TO NVU01, NVU02, NVU03, NVU04, NVRead, NVProfile;

-- Note: Adjust the specific user permissions as needed


